## Cost Landscape Exploration

&nbsp;

### Read the csv containing results from cost exploration:

In [16]:
import pandas as pd

df_1 = pd.read_csv("cost_exploration/yahpo_costs_test8.csv")
df_1["val_accuracy_scaled"] = df_1["val_accuracy"] * 0.01

df_2 = pd.read_csv("cost_exploration/yahpo_costs_train20.csv")
df_2["val_accuracy_scaled"] = df_2["val_accuracy"] * 0.01

### Get percentiles:

In [17]:
df_1["time"].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95])

count     8000.000000
mean       620.889716
std        969.755156
min         15.017196
10%         68.109850
25%        121.882799
50%        224.995178
75%        649.453156
90%       1807.979602
95%       2747.173816
max      12905.822266
Name: time, dtype: float64

In [18]:
df_2["time"].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95])

count    20000.000000
mean       269.836260
std        794.825975
min          8.320948
10%         49.826944
25%         72.275209
50%        123.880032
75%        245.530502
90%        599.726196
95%        866.830728
max      38462.175781
Name: time, dtype: float64

&nbsp;

### Grouping by instance:

In [19]:
df_1.groupby("instance")["time"].describe(
    percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95]
)

,count,mean,std,min,10%,25%,50%,75%,90%,95%,max
instance,,,,,,,,,,,
168331,1000.0,261.403632,321.478688,68.595551,108.699126,138.103615,183.495033,265.011261,430.413809,593.416144,4461.842773
168335,1000.0,389.636991,776.384528,24.011532,138.866682,167.504295,206.358078,334.143547,651.347711,1025.258307,12905.822266
168868,1000.0,272.428608,345.912468,21.109638,77.569241,109.145357,168.138428,290.590729,536.861688,783.248437,3923.659668
168908,1000.0,1925.064933,1045.960645,84.832764,149.415843,1457.640930,2275.448486,2785.964111,3027.251001,3117.824036,4339.551758
168910,1000.0,531.442615,295.031958,79.193520,132.929855,330.241112,542.834045,730.435669,849.893378,944.184613,2444.404053
189354,1000.0,1335.116189,1574.861450,240.911667,492.515585,558.146744,765.960510,1342.404663,2633.519385,4592.973926,12834.927734
189862,1000.0,133.581088,120.661976,15.501077,45.308442,61.050412,90.882671,151.162487,286.480875,377.849321,1139.773438
189865,1000.0,118.443673,111.011190,15.017196,39.155481,50.394217,79.660671,141.528790,253.327753,353.183627,963.721497

In [20]:
df_2.groupby("instance")["time"].describe(
    percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95]
)

,count,mean,std,min,10%,25%,50%,75%,90%,95%,max
instance,,,,,,,,,,,
3945,1000.0,245.770203,247.261699,43.542484,75.011228,115.062094,183.171516,269.809990,476.969037,645.526889,2878.204346
7593,1000.0,1681.759727,3056.204188,425.839386,575.754144,685.346848,929.247406,1502.606689,2729.530981,4362.041650,38462.175781
34539,1000.0,132.062786,117.841198,31.686695,60.463409,74.757715,91.512974,138.414936,246.966591,360.977068,1176.124512
126025,1000.0,160.787477,190.499126,34.525837,66.854827,77.457756,98.800476,168.295307,312.944446,459.609424,3381.067139
126026,1000.0,169.977794,159.756379,23.437008,55.808526,76.910429,114.610287,192.621143,368.577408,501.898000,1455.452271
126029,1000.0,160.909893,253.527423,35.474079,63.894086,74.764683,98.927372,164.093765,312.692621,474.291241,6160.429199
146212,1000.0,205.127815,264.718220,16.739368,41.628434,64.729376,116.091911,218.136467,477.168866,703.624121,2685.863525
167104,1000.0,87.340566,100.822390,11.267465,21.934328,28.828032,52.995600,94.602774,199.057886,311.438081,907.464417
167149,1000.0,92.167025,84.189011,8.320948,27.951886,38.674040,62.675318,108.673330,209.225531,268.102661,895.898682
167152,1000.0,169.195406,135.609376,23.202740,36.876776,88.721592,141.821983,202.020576,323.322250,453.980304,993.341492
167161,1000.0,101.541690,98.058958,19.651020,46.661914,58.166995,71.408890,102.091776,197.770653,275.926408,1895.562500
167168,1000.0,110.892058,90.888889,18.620506,37.269458,49.516746,80.731625,131.730198,246.544904,304.019011,681.893433
167181,1000.0,104.179006,86.968789,21.954685,45.110288,54.890686,70.591732,112.662560,222.422940,286.819545,745.750427
167184,1000.0,114.686486,89.004140,26.913425,54.646237,64.143698,82.061947,133.927185,205.569498,302.611765,937.028564
167185,1000.0,560.550821,305.640576,46.409515,100.969157,341.236870,597.037109,810.528824,920.833069,1009.010580,1532.124512
167190,1000.0,121.497756,118.722956,23.463505,51.037067,60.220005,77.897366,130.023365,248.066270,353.752502,1422.866333
167200,1000.0,314.581607,350.332321,77.789291,135.735670,157.778557,200.785072,312.894585,561.755048,937.230768,3056.522217
167201,1000.0,270.389464,326.642769,55.682747,83.324504,111.941273,164.457031,273.578537,549.670880,896.416632,3246.167480
168329,1000.0,304.436702,325.144182,85.866066,119.598723,148.167515,194.530182,318.874428,592.419904,849.654486,3596.879395
168330,1000.0,288.870917,424.520539,69.942604,97.733708,120.191656,180.736771,287.373703,565.601556,847.701385,7630.039551

&nbsp;

### Correlations

In [27]:
cols = [
    "time",
    "val_accuracy",
    "batch_size",
    "learning_rate",
    "max_dropout",
    "max_units",
    "momentum",
    "num_layers",
    "weight_decay",
]

df_together = pd.concat([df_1, df_2], ignore_index=True)

df_together[cols].corr(numeric_only=True)["time"].sort_values(ascending=False)

time             1.000000
num_layers       0.205064
max_units        0.177362
weight_decay     0.039667
learning_rate    0.034697
momentum         0.016446
max_dropout     -0.029033
batch_size      -0.058044
val_accuracy    -0.088610
Name: time, dtype: float64